apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    creationTimestamp: "2020-04-11T04:14:45Z"
    generation: 3
    name: ansible-awx-cli
    namespace: pipelines
    resourceVersion: "8631390"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/pipelines/tasks/ansible-awx-cli
    uid: 2cad6833-cf1a-4721-a96e-c70d838adeb2
  spec:
    inputs:
      params:
      - default: "false"
        description: Disable tower ssl verification
        name: SSLVERIFY
        type: string
      - default:
        - --help
        description: The awx-cli commands to tun
        name: ARGS
        type: array
      - default: ""
        description: The Ansible Tower host
        name: HOST
        type: string
      - default: tower-creds
        description: The Ansible Tower secret with credentials
        name: tower-secret
        type: string
    steps:
    - args:
      - |-
        echo -e "verify_ssl = $(inputs.params.SSLVERIFY)\nverbose = true\nhost = $(inputs.params.HOST)\nusername = $USER\npassword = $PASS" > ~/.awx_cli.cfg
        chmod 600 ~/.awx_cli.cfg
        echo "Generated awx_cli.cfg file"
        echo "-----------------------------"
        ls -lah ~/ | grep awx_cli
        echo "-----------------------------"
      command:
      - /bin/sh
      - -c
      env:
      - name: USER
        valueFrom:
          secretKeyRef:
            key: USER
            name: $(inputs.params.tower-secret)
      - name: PASS
        valueFrom:
          secretKeyRef:
            key: PASS
            name: $(inputs.params.tower-secret)
      image: quay.io/marcf5/ubiawx
      name: config
      resources: {}
    - args:
      - $(inputs.params.ARGS)
      command:
        - /bin/bash
      args:
        - -c
        - |
          awx -k --conf.host "https://10.19.41.9"  --conf.username "admin" --conf.password "password" --conf.insecure  workflow_job_templates launch "Workflow - Deploy and Register RHEL 8.1 KVM guests"
      image: quay.io/marcf5/ubiawx
      name: awx-cli
      resources: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
